myproject/feedback/urls.py
from django.urls import path
from . import views

app_name = 'feedback'

urlpatterns = [
    path('', views.submit_feedback, name='submit_feedback'),
    path('thank-you/', views.thank_you, name='thank_you'),
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path
from myapp.views import home
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('feedback/', include('feedback.urls')),
]

myproject/feedback/models.py
from django.db import models
from django.utils import timezone
import datetime


class Feedback(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    is_interesting = models.BooleanField(default=False)
    comments = models.TextField(blank=True, null=True)
    display_until = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f"Feedback #{self.id}"

myproject/myapp/models.py
from django.db import models

# Create your models here.
class Quote(models.Model):
    text = models.TextField()

    def __str__(self):
        return self.text

myproject/feedback/forms.py
# feedback/forms.py

from django import forms
from .models import Feedback

class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ['content']

myproject/feedback/views.py
# feedback/views.py
from django.shortcuts import render, redirect
from .forms import FeedbackForm
from .models import Feedback
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone

def thank_you(request):
    interesting_feedback = Feedback.objects.filter(is_interesting=True, display_until__gt=timezone.now()).order_by('-created_at')
    context = {
        'interesting_feedback': interesting_feedback,
    }
    return render(request, 'feedback/thank_you.html', context)

def submit_feedback(request):
    form = FeedbackForm(request.POST or None)
    interesting_feedback = Feedback.objects.filter(is_interesting=True, display_until__gt=timezone.now()).order_by('-created_at')
    context = {
        'form': form,
        'interesting_feedback': interesting_feedback,
    }
    if request.method == 'POST' and form.is_valid():
        form.save()
        return redirect('feedback:thank_you')

    return render(request, 'feedback/submit_feedback.html', context)

myproject/myapp/views.py
#views.py
from django.shortcuts import render
from .models import Quote
import random

def home(request):
    quotes = Quote.objects.all()
    random_quote = random.choice(quotes)

    context = {
        'random_quote': random_quote,
    }
    return render(request, 'myapp/home.html', context)

myproject/feedback/templates/feedback/submit_feedback.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid p-1">
    <div class="card bg-dark shadow card-body"> 
        <div class="row justify-content-center feedback-container">
            <section class="col-12 feedback-form my-2">
                <h1 class="text-center">What's on your mind?</h1>
                <div class="explainer-text">
                    <p>Don't hesitate to reach out with any questions, suggestions, or comments you might have. Anything that I find helpful, funny, interesting, or insightful, I'll be sure to share it on my website, while keeping it anonymous. It's a way to spread the goodness and let others benefit from it too.</p>
                    <p>Looking forward to seeing what you have to say!</p>
                </div>
                <form method="post" class="needs-validation" novalidate>
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_content">Feedback:</label>
                        {{ form.content }}
                    </div>
                    <button class="btn btn-primary btn-lg btn-block submit-button" type="submit">Submit</button>
                </form>
            </section>
    
            {% if interesting_feedback %}
                <section class="col-12 interesting-feedback my-2">
                    <h2 class="text-center">Check out what people have to say:</h2>
                    {% for feedback in interesting_feedback %}
                    <div class="card feedback-entry my-3">
                        <div class="card-header">
                            {{ feedback.created_at }}
                        </div>
                        <div class="card-body">
                            <p class="card-text">{{ feedback.content }}</p>
                        </div>
                        <div class="card-footer {% if feedback.comments %}comment-indent{% endif %}">
                            <p class="card-text">{{ feedback.comments }}</p>
                        </div>
                    </div>
                    {% endfor %}
                </section>
            {% endif %}

        </div>
    </div>
</div>
{% endblock %}

myproject/feedback/templates/feedback/thank_you.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid p-1">
    <div class="card bg-dark shadow card-body"> 
        <div class="row justify-content-center feedback-container">
            <section class="col-12 feedback-form my-2">
                <h1 class="text-center">Thank you!</h1>
            </section>
        
            {% if interesting_feedback %}
                <section class="col-12 interesting-feedback my-2">
                    <h2 class="text-center">Check out what people have to say:</h2>
                    {% for feedback in interesting_feedback %}
                    <div class="card feedback-entry my-3">
                        <div class="card-header">
                            {{ feedback.created_at }}
                        </div>
                        <div class="card-body">
                            <p class="card-text">{{ feedback.content }}</p>
                        </div>
                        <div class="card-footer comment-indent">
                            <p class="card-text">{{ feedback.comments }}</p>
                        </div>
                    </div>
                    {% endfor %}
                </section>
            {% endif %}
        </div>
    </div>
</div>

<!-- <script src="https://cdn.jsdelivr.net/npm/confetti.js"></script>
<script>
    // Display confetti effect on page load
    var confettiSettings = { target: 'confetti-canvas' };
    var confetti = new ConfettiGenerator(confettiSettings);
    confetti.render();

    // Stop confetti after a certain duration (in milliseconds)
    setTimeout(function() {
        confetti.clear();
    }, 5000);  // Adjust the duration as desired
</script> -->
{% endblock %}

myproject/myapp/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}My Home Page{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    {% load static %}
    <link href="{% static 'myapp/style.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>
<body class="kawaii-theme d-flex flex-column vh-100 ">
    <!-- Common header -->
    <!-- ... -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="{% url 'home' %}">Marcos Johnson-Noya</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
              <li class="nav-item">
                <a class="nav-link" href="https://github.com/middle-membership600" target="_blank">Github</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://soundcloud.com/marcos-johnson-noya" target="_blank"> SoundCloud</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% static 'myapp/Marcos Johnson-Noya 06:28:23 CV.pdf' %}" target="_blank">CV</a>
              </li>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'feedback:submit_feedback' %}">Feedback</a>
              </li>
            </ul>
          </div>
        </div>
      </nav> 
    <!-- Content section -->
    {% block content %}
    <!-- Default content if not overridden by child template -->
    {% endblock %}

    <footer class="bg-dark text-white mt-1">
        <div class="container py-5">
            <div class="row">
                <div class="col-6 col-lg-2 mb-3">
                    <h4 class="mb-4">Marcos JN</h4>
                    <p>mjohnsonnoya@college.harvard.edu</p>
                    <p>307-399-8601</p>
                </div>
                <div class="col-lg-8 text-center mb-3 d-none d-lg-block">
                    <h6 class="mb-4">{{ random_quote.text }}</h6>
                    <h2>—————————</h2>
                    <p>© 2023 Marcos Johnson-Noya. All rights reserved.</p>
                </div>
                <div class="col-6 col-lg-2 d-flex flex-column justify-content-start align-items-end align-items-lg-end mb-3">
                    <a href="https://www.instagram.com/elmarcosjn/" target="_blank" class="btn btn-outline-light mb-3">
                        <i class="fab fa-instagram"></i>
                    </a>
                    <a href="https://t.snapchat.com/lrtODk4S" target="_blank" class="btn btn-outline-light">
                        <i class="fab fa-snapchat"></i>
                    </a>                    
                </div>
            </div>
            <div class="row d-lg-none">
                <div class="col-12 col-lg-8 offset-lg-2 text-center mb-3">
                    <h2>———————————</h2>
                    <h6 class="mb-4" style="font-style: italic;">{{ random_quote.text }}</h6>
                    <p>© 2023 Marcos Johnson-Noya. All rights reserved.</p>
                </div>
            </div>
        </div>
    </footer>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
        <script>
            document.addEventListener('DOMContentLoaded', function() {
                var textElement = document.getElementById('typing-text');
                var text = "Hi there!";
        
                function typeWriter(text, i) {
                    if (i < text.length) {
                        textElement.innerHTML += text.charAt(i);
                        i++;
                        setTimeout(function() {
                            typeWriter(text, i);
                        }, 100); // Adjust the typing speed here (in milliseconds)
                    }
                }
        
                typeWriter(text, 0);
            });
        </script>

    <!-- Common footer -->
    <!-- ... -->

    <!-- Include common scripts -->
    <!-- ... -->
</body>
</html>

myproject/myapp/templates/myapp/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid p-1">
    <div class="card bg-dark shadow card-body">
        <div class="row g-0">
            <div class="col-sm-12 col-md-6">
                <img src="{% static 'myapp/images/marcos.png' %}" alt="My Image" class="img-fluid rounded-start">
            </div>
            <div class="col-sm-12 col-md-6">
                <div class="card-body">
                    <h1 class="card-title">
                        <span class="typing-text"></span>
                    </h1>
                    
                    <p class="card-text">I'm an undergraduate at Harvard studying computer science and Spanish. </p>
                    <h2 class="card-title mt-custom">
                        Life Updates and Fun Facts
                    </h2>

                    <ul>
                        <li>05/14/23: Finished first year at college!</li>
                        <li><strong>Favorite Song:</strong> Home Resonance</li>
                        <li>02/15/23: Went on retreat to Maine as a part of Hoffman Lab</li>
                    </ul>
                </div>
            </div>
        </div>
        
    </div>
</div>

<div class="container-fluid p-1">
    <div class="card bg-dark shadow card-body">
        <div class="row g-0">
            <div class="col-md-1"></div>
            <div class="col-md-10">
                <h2 class="text-center"> Adventurer, innovator, researcher.</h2>

                <p>Currently, I'm deeply engaged in enhancing the efficiency of scanning tunneling microscopy, and in doing so, pushing the frontiers of quantum science at Hoffman Labs and the Harvard Quantum Initiative. During my downtime, I'm putting together my first EP for Soundcloud, while persistently working on self-improvement and self-directed learning.</p>
                
                <p>
                    Raised in Southeast Wyoming, home to the University of Wyoming, I was shaped by its peaceful and natural environment. My household, blending cultures from California and Spain, instilled in me a curiosity and appreciation for diversity.</p>
                
                <h4>I have a deep interest in:</h4>
                <ul>
                    <li>Environmentally sustainable technology</li>
                    <li>Spanish and multilingual education</li>
                    <li>Eating healthy</li>
                    <li>AI & its intersection with the humanities</li>
                </ul>
                
                <h4>Some things I love:</h4>
                <ul>
                    <li>Tennis & Rafael Nadal</li>
                    <li>Spanish literature</li>
                    <li>Cello & electronic music production (currently: classical, lo-fi)</li>
                    <li>Sketch comedy</li>
                    <li>Photoshop & digital media</li>
                    <li>Basketball & the Denver Nuggets</li>
                </ul>
            </div>
            <div class="col-md-1"></div>
        </div>
    </div>
</div>

<!-- CSS -->
<style>
@keyframes typing {
  from { width: 0; }
  to { width: 100%; }
}

.typing-text::after {
  content: '|';
  animation: typing 1s steps(1) infinite;
}

.typing-text::after {
  content: '';
  animation: none;
  visibility: hidden;
}
</style>

<!-- JavaScript -->
<script>
// JavaScript code to start the typing animation
document.addEventListener('DOMContentLoaded', function() {
    const typingText = document.querySelector('.typing-text');
    const textToType = 'Hi there!';

    let i = 0;
    function typeText() {
        if (i < textToType.length) {
            typingText.textContent += textToType.charAt(i);
            i++;
            setTimeout(typeText, 100);
        }
    }

    typeText();
});
</script>
{% endblock %}